import Link from "next/link";

export default function HomePage() {
  return (
    <div>
      <h1 className='text-fuchsia-500'>Welcome to the Next.js app!</h1>
      <p>This is a simple Next.js app that was generated by Create Next App.</p>

      <Link href='/properties'> Go To Properties</Link>
    </div>
  );
}
